name: raydart
description: Raylib dart test.
version: 1.0.0
homepage: https://github.com/bdero/raydart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  ffigen: ^3.0.0
  pedantic: ^1.10.0

ffigen:
  output: 'src/generated/raylib.dart'
  headers:
    entry-points:
      - 'deps/raylib/src/raylib.h'
    #include-directives:
    #  - 'deps/raylib/src/**.h'
dependencies:
  ffi: ^1.1.2
  path: ^1.8.0
