name: raydart
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  ffigen: ^3.0.0
  pedantic: ^1.10.0

ffigen:
  output: 'raylib.dart'
  headers:
    entry-points:
      - 'deps/raylib/src/raylib.h'
dependencies: 
  ffi: ^1.1.2
    #include-directives:
    #  - 'deps/raylib/src/**.h'

